
server:
  port: 8080



  #mail
spring:
  mail:
    host: smtp.exmail.qq.com
    username: 发送者的邮箱
    password: wefwf234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
    default-cc: 默认邮箱
  #freemarker
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl